version: '3.8'

services:
  backend:
    build:
      context: ./
    image: your-dockerhub-username/django-backend:latest
    container_name: django-backend
    restart: always
    
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
